model:
  backbone: timm_tf_efficientnet_b5.ns_jft_in1k
  ckpt_pretrained: 
  num_classes: 2 # needs to be entered here unlike stage 1 

train:
  n_epochs: &epochs 100
  amp: True # set this to True, if your GPU supports FP16. 2080Ti - okay, 1080Ti - not okay
  ema: True # optional, but I recommend it, since the training might get unstable otherwise
  ema_decay_per_epoch: 0.4 # for middle/big datasets. Increase, if you have low amount of samples
  target_metric: accuracy
  stage: second # first = Supcon, second = FC finetuning for classification

dataloaders:
  train_batch_size: 30 # the higher - the better
  valid_batch_size: 21
  num_workers: 0 # set this to num of threads in your CPU

optimizer:
  name: SGD
  params:
    lr: 0.3
  
scheduler:
  name: CosineAnnealingLR
  params:
    T_max: *epochs
    eta_min: 0.002 # Make sure it is smaller than lr

criterion:
  name: 'LabelSmoothing'
  params:
    classes: 100
    smoothing: 0.01

img_size: &size 384

augmentations:
  transforms: 
    - RandomResizedCrop:
        height: *size
        width: *size 
        scale:  !!python/tuple [0.7,1]
    - Flip:
    - RandomRotate90:
    - MedianBlur:
        blur_limit: 3
        p: 0.3
    - ShiftScaleRotate:
        p: 0.4
    - OpticalDistortion:
    - GridDistortion:
    - HueSaturationValue:
